config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root to: 'dashboards#show'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # Submissions routes
  get 'submissions/new/:workout_post_id', to: 'submissions#new', as: 'new_submission'
  get 'submissions/edit/:workout_post_id', to: 'submissions#edit', as: 'edit_submission'
  post 'submissions/create', to: 'submissions#create'
  post 'submissions/update', to: 'submissions#update'

  get 'submissions/history/:workout_post_id', to: 'submissions#history', as: 'submissions_history'

  # Posts routes
  get 'posts/new/', to: 'posts#new', as: 'posts_new'
  get 'posts/edit/:workout_post_id', to: 'posts#edit', as: 'edit_post'
  post 'posts/create/', to: 'posts#create'
  post 'posts/update', to: 'posts#update'
  post 'posts/archive/:workout_post_id', to: 'posts#archive', as: 'archive_post'

  # Permissions routes
  get 'permissions/', to: 'permissions#index', as: 'permissions'
  post 'permissions/', to: 'permissions#complete'
  get 'permissions/archived/', to: 'permissions#archived', as: 'archived_profiles'

  # Profiles routes
  get 'profiles/:id/', to: 'profiles#show', as: 'profiles'
  get 'profiles/:id/edit/', to: 'profiles#edit', as: 'edit_profile'
  post 'profiles/:id/', to: 'profiles#update'
  post 'profiles/:id/archive', to: 'profiles#archive', as: 'archive_user'
  post 'profiles/:id/restore', to: 'profiles#restore', as: 'restore_user'

  get 'members/', to: 'members#index', as: 'members'

  # Admin-only routes for setting WOD dates
  get '/wod/set', to: 'wod#admin_view', as: 'set_wod'
  post '/wod/set', to: 'wod#update_wod'

  # User route for viewing the current and past WODs
  get '/wod', to: 'wod#user_view', as: 'user_wod'

  # Leaderboard and Fistbump routes
  get 'leaderboard', to: 'dashboards#leaderboard', as: 'leaderboard'
  post 'leaderboard/like/:exercise_submission_id', to: 'dashboards#like', as: 'leaderboard_like'
  post 'leaderboard/unlike/:exercise_submission_id', to: 'dashboards#unlike', as: 'leaderboard_unlike'

  get 'documentation', to: 'documentation#index'

  get 'exercises/archived', to: 'exercises#archived', as: 'archived_exercises'
  post 'exercises/:id/archive', to: 'exercises#archive', as: 'archive_exercise'
  post 'exercises/:id/restore', to: 'exercises#restore', as: 'restore_exercise'

  resources :exercises
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/permissions_controller.rb
# frozen_string_literal: true

class PermissionsController < ApplicationController
  before_action :require_admin

  def index
    @users = User.not_permanent_admin
  end

  def complete
    submitted_hash = params[:user]

    permanent_admin = User.where(email: 'tamuocr@gmail.com').first
    submitted_hash = submitted_hash.except(permanent_admin.id) if permanent_admin

    User.update(submitted_hash.keys, submitted_hash.values.map { |x| { is_admin: x[:is_admin] } })
    respond_to do |format|
      format.html { redirect_to permissions_url }
    end
  end

  def archived
    @users = User.archived
  end
end

app/views/permissions/archived.html.erb
<!DOCTYPE html>
<html>

    <% if flash.any? %>
    <% flash.each do |key, value| -%>
      <section class="flash flash__<%= key %>"><%= value.html_safe %></section>
    <% end -%>
    <% end %>

    <head>
    <%= stylesheet_link_tag  'permissions', media: 'all', 'data-turbolinks-track': 'reload' %>
    </head>

    <body id="permissions-page">
    
        
        <h1>Archived Users</h1>
        
        <div class="container-fluid justify-content-center">

            <div class = "row">

            <div class="col-1 col-lg-2">
                <br>
            </div>

            <div class="content col-10 col-lg-8">
                <input type="text" size="30" style="margin-bottom: 3%; border-radius: 10px; border: none;" id="inputName" onkeyup="searchName()" placeholder=" Search by TAMU email" title="Type in a name">
                <%=="<a class='float-end' href='#{permissions_path}'> View active users</a> "%>
                <table id="userTable">
                <tr>
                <th>Email</th>
                <th>Name</th>
                <th style="text-align: center">Restore</th>
                </tr>
                <% @users.each do |user| %>
                    <tr>
                    <td><%= user.email %></td>
                    <td><%= user.full_name %></td>
                    <td style="text-align: center;"><%= link_to "Restore", restore_user_path(user.id), method: :post, data: {confirm: "Are you sure you want to restore #{user.full_name}?"} %></td>
                    </tr>
                <% end %>
                </table>
                <br>
            </div>

            <div class="col-1 col-lg-2">
                <br>
            </div>

            </div>
        </div>
    </body>

</html>

<script>
function searchName() {
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("inputName");
  filter = input.value.toUpperCase();
  table = document.getElementById("userTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>

app/views/permissions/index.html.erb
<!DOCTYPE html>
<html>

    <% if flash.any? %>
    <% flash.each do |key, value| -%>
      <section class="flash flash__<%= key %>"><%= value.html_safe %></section>
    <% end -%>
    <% end %>

    <head>
    <%= stylesheet_link_tag  'permissions', media: 'all', 'data-turbolinks-track': 'reload' %>
    </head>

    <body id="permissions-page">
    <%= form_with url:"/permissions", method: :post do |perm_form| %>

        <h1>Permissions</h1>

        <div class="container-fluid justify-content-center">

          <div class = "row">

            <div class="col-1 col-lg-2">
              <br>
            </div>

            <div class="content col-10 col-lg-8">

                <input type="text" size="30" style="margin-bottom: 3%; border-radius: 10px; border: none;" id="inputName" onkeyup="searchName()" placeholder=" Search by TAMU email" title="Type in a name">
                <%=="<a class='float-end' href='#{archived_profiles_path}'> View archived users</a> "%>
              <table id="userTable">
              <tr>
                <th>Email</th>
                <th>Name</th>
                <th style="text-align: center">Admin</th>
                <th style="text-align: center">Archive</th>
              </tr>
                <% @users.each do |user| %>
                  <%= perm_form.fields_for user, index: user.id, method: :post do |p_fields|%>
                  <tr>
                    <td><%= user.email %></td>
                    <td><%= link_to "#{user.full_name}",  "/profiles/#{user.id}"%></td>
                    <td style="text-align: center;"><%= p_fields.check_box :is_admin %></td>
                    <td style="text-align: center;"><%= link_to "Archive", archive_user_path(user.id), method: :post, data: {confirm: "Are you sure you want to archive #{user.full_name}?"} %></td>
                  </tr>
                  <% end %>
                <% end %>
              </table>
              <br>
              <%= perm_form.submit 'Save Changes', :class => "form1" %>
            </div>

            <div class="col-1 col-lg-2">
              <br>
            </div>

          </div>
        </div>
      <% end %>
    </body>

</html>

<script>
function searchName() {
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("inputName");
  filter = input.value.toUpperCase();
  table = document.getElementById("userTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>