config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root to: 'dashboards#show'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # Submissions routes
  get 'submissions/new/:workout_post_id', to: 'submissions#new', as: 'new_submission'
  get 'submissions/edit/:workout_post_id', to: 'submissions#edit', as: 'edit_submission'
  post 'submissions/create', to: 'submissions#create'
  post 'submissions/update', to: 'submissions#update'

  get 'submissions/history/:workout_post_id', to: 'submissions#history', as: 'submissions_history'

  # Posts routes
  get 'posts/new/', to: 'posts#new', as: 'posts_new'
  get 'posts/edit/:workout_post_id', to: 'posts#edit', as: 'edit_post'
  post 'posts/create/', to: 'posts#create'
  post 'posts/update', to: 'posts#update'
  post 'posts/archive/:workout_post_id', to: 'posts#archive', as: 'archive_post'

  # Permissions routes
  get 'permissions/', to: 'permissions#index', as: 'permissions'
  post 'permissions/', to: 'permissions#complete'
  get 'permissions/archived/', to: 'permissions#archived', as: 'archived_profiles'

  # Profiles routes
  get 'profiles/:id/', to: 'profiles#show', as: 'profiles'
  get 'profiles/:id/edit/', to: 'profiles#edit', as: 'edit_profile'
  post 'profiles/:id/', to: 'profiles#update'
  post 'profiles/:id/archive', to: 'profiles#archive', as: 'archive_user'
  post 'profiles/:id/restore', to: 'profiles#restore', as: 'restore_user'

  get 'members/', to: 'members#index', as: 'members'

  # Admin-only routes for setting WOD dates
  get '/wod/set', to: 'wod#admin_view', as: 'set_wod'
  post '/wod/set', to: 'wod#update_wod'

  # User route for viewing the current and past WODs
  get '/wod', to: 'wod#user_view', as: 'user_wod'

  # Leaderboard and Fistbump routes
  get 'leaderboard', to: 'dashboards#leaderboard', as: 'leaderboard'
  post 'leaderboard/like/:exercise_submission_id', to: 'dashboards#like', as: 'leaderboard_like'
  post 'leaderboard/unlike/:exercise_submission_id', to: 'dashboards#unlike', as: 'leaderboard_unlike'

  get 'documentation', to: 'documentation#index'

  get 'exercises/archived', to: 'exercises#archived', as: 'archived_exercises'
  post 'exercises/:id/archive', to: 'exercises#archive', as: 'archive_exercise'
  post 'exercises/:id/restore', to: 'exercises#restore', as: 'restore_exercise'

  resources :exercises
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/exercises_controller.rb
# frozen_string_literal: true

# Exercises Controller
class ExercisesController < ApplicationController
  before_action :require_admin # , only: %i[ edit update destroy ]
  before_action :set_exercise, only: %i[show edit update destroy archive]

  # GET /exercises
  def index
    @exercises = Exercise.not_archived.order('updated_at DESC')
  end

  # GET /exercises/1
  def show; end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit; end

  # POST /exercises
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # @exercise.destroy
    # respond_to do |format|
    #   format.html { redirect_to exercises_path, notice: 'Exercise was successfully destroyed' }
    #   format.json { head :no_content }
    # end
  end

  def archive
    exercise = Exercise.find(params[:id])
    respond_to do |format|
      if exercise.archive
        format.html { redirect_to exercises_path, notice: 'Exercise archived successfully' }
      else
        format.html { redirect_to exercise_path(exercise.id), notice: 'Exercise could not be archived' }
      end
    end
  end

  def restore
    exercise = Exercise.find(params[:id])
    respond_to do |format|
      if exercise.un_archive
        format.html { redirect_to exercises_path, notice: 'Exercise restored successfully' }
      else
        format.html { redirect_to exercise_path(exercise.id), notice: 'Exercise could not be restored' }
      end
    end
  end

  def archived
    @exercises = Exercise.archived.order('updated_at DESC')
  end

  private

  def set_exercise
    @exercise = Exercise.find(params[:id])
  end

  def exercise_params
    params.require(:exercise).permit(:title, :description, :picture, :unit_name, :image)
  end
end

app/views/exercises/_form.html.erb
<%= form_with(model: exercise) do |form| %>

  <% if exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
        <% exercise.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h2 style="text-align: center;">

      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control'%>

  </h2>
  <br>

  <h2 style="text-align: center;">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control'%>
  </h2>

  <br>

  <p style="text-align: center;">
    <%= form.label :unit_name %>
    <%= form.select :unit_name, Exercise.unit_names.map{|key, value| [value, key]} %>
  </p>
  <br>

  <div class="field">
    <% if exercise.image.attached? %>
      <%= cl_image_tag exercise.image.key, style: "width: 100px; display: block" %>
    <% end %>
    <%= form.file_field :image, style: "display: block" %>
  </div>
  <br>



  <%= form.submit "Submit", :class => "universal-button", :style => "margin-right: 0%; display: inline; float: right; display: flex; flex-wrap: wrap;"%>




<% end %>

app/views/exercises/archived.html.erb
<!DOCTYPE html>
<html>

  <head>
      <%= stylesheet_link_tag  'exercises', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="exercises">
    <h1>Archived Exercises</h1>

    <div class="container-fluid">
      <div class = "row">

        <div class="col-1 col-lg-2">
          <br>
        </div>

        <div class="content col-10 col-lg-8">
          <%= button_to "New Exercise", new_exercise_path, :method => "get",:class => "universal-button", :style => "" %>
          <%=="<a class='float-end' href='#{exercises_path}'> View active exercises</a> "%>
          <%# button_to "View active exercises", exercises_path, :method => "get",:class => "universal-button float-end", :style => "" %>
          <br>
          <div class="table-responsive">
            <table>
              <thead>
                <tr>
                <th style="text-align:center">Title</th>
                <th style="text-align:center">Unit Name</th>
                <th></th>
                </tr>
              </thead>

              <tbody>
                <% @exercises.each do |exercise| %>
                  <tr style='border-bottom: 1px solid #ffffff;'>
                    <td style="text-align:center"><%= exercise.title %></td>
                    <td style="text-align:center"><%= exercise.humanized_unit_name %></td>
                     <td class="text-center">
                    <%= button_to "Show", exercise_path(exercise), :method => "get",:class => "universal-button"%>
                    <%= button_to "Edit", edit_exercise_path(exercise), :method => "get",:class => "universal-button"%>
                    </td>
                    <td style="text-align: center;"><%= link_to "Restore", restore_exercise_path(exercise.id), method: :post, data: {confirm: "Are you sure you want to restore #{exercise.title}?"} %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>

        <div class="col-1 col-lg-2">
          <br>
        </div>

      </div>

    </div>
  </body>
</html>

app/views/exercises/edit.html.erb
<!DOCTYPE html>
<html>

    <head>
        <%= stylesheet_link_tag  'exercises', media: 'all', 'data-turbolinks-track': 'reload' %>
    </head>

    <body id="exercises">
        
        <h1>Edit Exercise</h1>
        
        <div class="container-fluid">
            <div class = "row">
                <div class="col-1 col-lg-2">
                    <br>
                </div>

                <div class="content col-10 col-lg-8">
                    <%= render 'form', exercise: @exercise %>
                    <%= button_to "Back", exercises_path, :method => "get",:class => "universal-button", :style => "margin-left: 0%; display: inline; float: left; display: flex; flex-wrap: wrap;" %>
                    <br>
                    <br>
                    <hr>
                <%= button_to "Archive Exercise", archive_exercise_path(@exercise.id), :method => "post",:class => "universal-button", :style => "margin-left: 0%; display: block; float: left; display: flex; flex-wrap: wrap;", data: {confirm: "Are you sure you want to archive #{@exercise.title}?"} %>
                </div>

                <div class="col-1 col-lg-2">
                    <br>
                </div>
            </div>
        </div>
    </body>
</html>


app/views/exercises/index.html.erb
<!DOCTYPE html>
<html>

  <head>
      <%= stylesheet_link_tag  'exercises', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="exercises">
    <h1>Exercises</h1>

    <div class="container-fluid">
      <div class = "row">

        <div class="col-1 col-lg-2">
          <br>
        </div>

        <div class="content col-10 col-lg-8">
          <%= button_to "New Exercise", new_exercise_path, :method => "get",:class => "universal-button", :style => "" %>
          <%=="<a class='float-end' href='#{archived_exercises_path}'> View archived exercises</a> "%>
          <%# button_to "View archived exercises", archived_exercises_path, :method => "get",:class => "universal-button float-end", :style => "" %>
          <br>
          <div class="table-responsive">
            <table>
              <thead>
                <tr>
                  <th style="text-align:center">Title</th>
                  <th style="text-align:center">Unit Name</th>
                  <th></th>
                </tr>
              </thead>

              <tbody>
                <% @exercises.each do |exercise| %>
                  <tr style='border-bottom: 1px solid #ffffff;'>
                    <td style="text-align:center"><%= exercise.title %></td>
                    <td style="text-align:center"><%= exercise.humanized_unit_name %></td>
                    <td class="text-center">
                    <%= button_to "Show", exercise_path(exercise), :method => "get",:class => "universal-button"%>
                    <%= button_to "Edit", edit_exercise_path(exercise), :method => "get",:class => "universal-button"%>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>

        <div class="col-1 col-lg-2">
          <br>
        </div>

      </div>

    </div>
  </body>
</html>

app/views/exercises/new.html.erb
<!DOCTYPE html>
<html>

    <head>
        <%= stylesheet_link_tag  'exercises', media: 'all', 'data-turbolinks-track': 'reload' %>
    </head>

    <body id="exercises">

        <h1>New Exercise</h1>

        <div class="container-fluid">
            <div class = "row">
                <div class="col-1 col-lg-2">
                    <br>
                </div>

                <div class="content col-10 col-lg-8">
                    <%= render 'form', exercise: @exercise %>
                    <%= button_to 'Back', exercises_path, :method => "get", :class => "universal-button", :style => "margin-left: 0%; display: inline; float: left; display: flex; flex-wrap: wrap;"%>
                </div>

                <div class="col-1 col-lg-2">
                    <br>
                </div>
            </div>
        </div>

    </body>

</html>

app/views/exercises/show.html.erb
<!DOCTYPE html>
<html>

  <head>
      <%= stylesheet_link_tag  'exercises', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="exercises">
    <h1>Exercise Information</h1>

    <div class="container-fluid">
      <div class = "row">

        <div class="col-1 col-lg-3">
          <br>
        </div>

        <div class="content col-10 col-lg-6" id="show">
          <p style="text-align: center;">
            <strong>Title:</strong>
            <%= @exercise.title %>
          </p>
          <p style="text-align: center;">
            <strong>Description:</strong>
            <%= @exercise.description %>
          </p>
          <p style="text-align: center;">
            <strong>Image:</strong>
            <% if @exercise.image.attached? %>
              <%= cl_image_tag @exercise.image.key, style: "width: 100px; display: block; margin-left: auto; margin-right: auto;" %>
            <% end %>
          </p>
          <p style="text-align: center;">
            <strong>Unit Name:</strong>
            <%= @exercise.humanized_unit_name %>
          </p>
          <%= button_to "Back", exercises_path, :method => "get",:class => "universal-button", :style => "margin-left: 0%; display: inline; float: left; display: flex; flex-wrap: wrap;" %>
          <%= button_to "Edit", edit_exercise_path(@exercise), :method => "get",:class => "universal-button", :style => "margin-left: 0%; display: inline; float: right; display: flex; flex-wrap: wrap; margin-right: 2%" %>
          <br>
        </div>

        <div class="col-1 col-lg-3">
          <br>
        </div>

      </div>
    </div>
  </body>
</html>