config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root to: 'dashboards#show'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # Submissions routes
  get 'submissions/new/:workout_post_id', to: 'submissions#new', as: 'new_submission'
  get 'submissions/edit/:workout_post_id', to: 'submissions#edit', as: 'edit_submission'
  post 'submissions/create', to: 'submissions#create'
  post 'submissions/update', to: 'submissions#update'

  get 'submissions/history/:workout_post_id', to: 'submissions#history', as: 'submissions_history'

  # Posts routes
  get 'posts/new/', to: 'posts#new', as: 'posts_new'
  get 'posts/edit/:workout_post_id', to: 'posts#edit', as: 'edit_post'
  post 'posts/create/', to: 'posts#create'
  post 'posts/update', to: 'posts#update'
  post 'posts/archive/:workout_post_id', to: 'posts#archive', as: 'archive_post'

  # Permissions routes
  get 'permissions/', to: 'permissions#index', as: 'permissions'
  post 'permissions/', to: 'permissions#complete'
  get 'permissions/archived/', to: 'permissions#archived', as: 'archived_profiles'

  # Profiles routes
  get 'profiles/:id/', to: 'profiles#show', as: 'profiles'
  get 'profiles/:id/edit/', to: 'profiles#edit', as: 'edit_profile'
  post 'profiles/:id/', to: 'profiles#update'
  post 'profiles/:id/archive', to: 'profiles#archive', as: 'archive_user'
  post 'profiles/:id/restore', to: 'profiles#restore', as: 'restore_user'

  get 'members/', to: 'members#index', as: 'members'

  # Admin-only routes for setting WOD dates
  get '/wod/set', to: 'wod#admin_view', as: 'set_wod'
  post '/wod/set', to: 'wod#update_wod'

  # User route for viewing the current and past WODs
  get '/wod', to: 'wod#user_view', as: 'user_wod'

  # Leaderboard and Fistbump routes
  get 'leaderboard', to: 'dashboards#leaderboard', as: 'leaderboard'
  post 'leaderboard/like/:exercise_submission_id', to: 'dashboards#like', as: 'leaderboard_like'
  post 'leaderboard/unlike/:exercise_submission_id', to: 'dashboards#unlike', as: 'leaderboard_unlike'

  get 'documentation', to: 'documentation#index'

  get 'exercises/archived', to: 'exercises#archived', as: 'archived_exercises'
  post 'exercises/:id/archive', to: 'exercises#archive', as: 'archive_exercise'
  post 'exercises/:id/restore', to: 'exercises#restore', as: 'restore_exercise'

  resources :exercises
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/wod_controller.rb
# frozen_string_literal: true

# WOD Controller
class WodController < ApplicationController
  before_action :set_recent_workout_posts, only: %i[admin_view]
  before_action :require_admin, only: %i[admin_view update_wod]
  before_action :set_all_current_or_past_wps_with_wod_dates, only: %i[user_view]

  # GET /wod/set
  def admin_view; end

  # POST /wod/set
  def update_wod
    submitted_hash = params[:workout_post]

    WorkoutPost.update(submitted_hash.keys, submitted_hash.values.map { |x| { wod_date: x[:wod_date] } })
    respond_to do |format|
      format.html { redirect_to set_wod_path, notice: 'WOD dates successfully updated' }
    end
  end

  # GET /wod
  def user_view; end

  private

  def set_recent_workout_posts
    @workout_posts = WorkoutPost.recent_workout_posts
  end

  def set_all_current_or_past_wps_with_wod_dates
    @workout_posts = WorkoutPost.current_or_past_wod
    @current_submission = WorkoutSubmission.where(user_id: current_user.id, workout_post_id: WorkoutPost.current_wod)
  end
end

app/views/wod/admin_view.html.erb
<!DOCTYPE html>
<html>

    <head>
        <%= stylesheet_link_tag  'wod', media: 'all', 'data-turbolinks-track': 'reload' %>
    </head>

    <body id="wod">

        <h1>Set WOD Dates</h1>

        <div class="container-fluid">
            <div class = "row">

                <div class="col-1 col-lg-2">
                    <br>
                </div>

                <div class="content col-10 col-lg-8">
            
                    <%= form_with url: set_wod_path, method: :post do |wp_h_form|%>
                        <%= wp_h_form.submit 'Set WOD dates', :class => "universal-button" %> 
                        <table>
                        <tr>
                            <th>Name</th>
                            <th>Details</th>
                        </tr>
                        <% @workout_posts.each do |wp| %>
                            <% if wp.archived == false %>
                                <%= wp_h_form.fields_for wp, url: set_wod_path, index: wp.id, method: :post do |wp_fields|%>
                                    <tr>
                                        <td><%= wp_fields.label :wod_date, wp.title%></td>
                                        <td>
                                        
                                        <% wp.exercise_posts.each do |ep|%>

                                        
                                        <%= '*' if ep.is_ranked?%>
                                        <%=ep.exercise.title%>
                                        <%= ": #{truncate(ep.specific_instructions, length: 25)}" %>
                                        <br>
                                        <% end %>
                                        
                                        </td>

                                        <td style="text-align: center; vertical-align: middle;"><input class ="universal-button" type="button" value="Clear" id='<%= "clear_button_#{wp.id}" %>'  onclick="this.parentElement.parentElement.nextElementSibling.firstElementChild.firstChild.value =''"></td>
                                    </tr>
                                    <tr style='border-bottom: 1px solid #ffffff;'>
                                        <td><%= wp_fields.datetime_local_field :wod_date %></td>
                                        <td>
                                            <%= link_to "Archive Post", archive_post_path(wp), method: :post, data: {confirm: "Are you sure you want to archive #{wp.title}?"} %>
                                        </td>
                                        <% if wp.workout_submissions.empty? %>
                                            <td>
                                            <a href="<%= edit_post_path(wp) %>">Edit Post</a>
                                            </td>
                                        <% end %>
                                    </tr>
                                    
                                    
                                <% end %> 
                            <% end %>

                        <%end%>

                        </table>
                        <br>
                        

                    <% end %>   
                </div>

                <div class="col-1 col-lg-2">
                    <br>
                </div>

            </div>   
        </div>
    </body>

</html>

app/views/wod/index.html.erb
<h1>Set WOD dates</h1>

<%= form_with url: set_wod_path, method: :post do |wp_h_form|%>

    <% @workout_posts.each do |wp| %>

        <%= wp_h_form.fields_for wp, url: set_wod_path, index: wp.id, method: :post do |wp_fields|%>
            <%= wp_fields.label :wod_date, wp.title%>
            <%= wp_fields.datetime_local_field :wod_date %> 
            <input type="button" value="Clear" id='<%= "clear_button_#{wp.id}" %>'  onclick="this.previousElementSibling.value =''">

        <% end %> 
        <br>

    <%end%>

    <%= wp_h_form.submit 'Set WOD dates' %> 

<% end %>

app/views/wod/user_view.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag  'wod', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body id="wod">
    <h1>View Workout of the Day</h1>
    <div class="container-fluid">
      <div class = "row">
        <div class="col-1 col-lg-2">
          <br>
        </div>
        <div class="content col-10 col-lg-8">
          <% if flash.any? %>
            <% flash.each do |key, value| -%>
              <section class="flash flash__<%= key %>"><%= value.html_safe %></section>
            <% end -%>
          <% end %>
          <% @workout_posts.each do |wp| %>
            <h2>
              <% if wp == @workout_posts.first %>
                <% if @current_submission.empty? %>
                  <%=="Current: #{wp.title}"%>
                <% else %>
                  <%=="Current: #{wp.title}"%>
                <% end %>
                <%#"<a href='#{submissions_history_path(wp)}'>View submissions history</a>"%>
              <% elsif current_user.is_admin? %>
                <%=wp.title%>
              <% else %>
                <%=wp.title%>
              <% end %>
              <%=wp.humanized_wod_date%>
              <br>
            </h2>
            <% wp.exercise_submissions_to_this_post_for_current_user(current_user).each do |es| %>
              <p><%="#{es.exercise.title}: #{es.humanized_unit_value}"%></p>
            <% end %>
            <div class="row">
              <div class="col">
                <% if wp == @workout_posts.first %>
                  <% if @current_submission.empty? %>
                    <%= button_to "Submit Scores", new_submission_path(wp), :method => "get",:class => "universal-button", :style => "margin-left: 0%; display: inline; float: left; display: flex; flex-wrap: wrap;" %>
                  <% else %>
                    <%= button_to "Edit Scores", edit_submission_path(wp), :method => "get",:class => "universal-button", :style => "margin-left: 0%; display: inline; float: left; display: flex; flex-wrap: wrap;" %>
                  <% end %>
                <% end %>
                </div>
            <% if current_user.is_admin? %>
              <div class="col">
                <%= button_to "View History", submissions_history_path(wp), :method => "get",:class => "universal-button", :style => "margin-right: 0%; display: inline; float: right; display: flex; flex-wrap: wrap;" %>
              </div>
            <% end %>
            </div>
          <hr>
          <br>
        <% end %>
      </div>
      <div class="col-1 col-lg-2">
        <br>
      </div>
    </div>
  </div>
</body>
</html>