config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root to: 'dashboards#show'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # Submissions routes
  get 'submissions/new/:workout_post_id', to: 'submissions#new', as: 'new_submission'
  get 'submissions/edit/:workout_post_id', to: 'submissions#edit', as: 'edit_submission'
  post 'submissions/create', to: 'submissions#create'
  post 'submissions/update', to: 'submissions#update'

  get 'submissions/history/:workout_post_id', to: 'submissions#history', as: 'submissions_history'

  # Posts routes
  get 'posts/new/', to: 'posts#new', as: 'posts_new'
  get 'posts/edit/:workout_post_id', to: 'posts#edit', as: 'edit_post'
  post 'posts/create/', to: 'posts#create'
  post 'posts/update', to: 'posts#update'
  post 'posts/archive/:workout_post_id', to: 'posts#archive', as: 'archive_post'

  # Permissions routes
  get 'permissions/', to: 'permissions#index', as: 'permissions'
  post 'permissions/', to: 'permissions#complete'
  get 'permissions/archived/', to: 'permissions#archived', as: 'archived_profiles'

  # Profiles routes
  get 'profiles/:id/', to: 'profiles#show', as: 'profiles'
  get 'profiles/:id/edit/', to: 'profiles#edit', as: 'edit_profile'
  post 'profiles/:id/', to: 'profiles#update'
  post 'profiles/:id/archive', to: 'profiles#archive', as: 'archive_user'
  post 'profiles/:id/restore', to: 'profiles#restore', as: 'restore_user'

  get 'members/', to: 'members#index', as: 'members'

  # Admin-only routes for setting WOD dates
  get '/wod/set', to: 'wod#admin_view', as: 'set_wod'
  post '/wod/set', to: 'wod#update_wod'

  # User route for viewing the current and past WODs
  get '/wod', to: 'wod#user_view', as: 'user_wod'

  # Leaderboard and Fistbump routes
  get 'leaderboard', to: 'dashboards#leaderboard', as: 'leaderboard'
  post 'leaderboard/like/:exercise_submission_id', to: 'dashboards#like', as: 'leaderboard_like'
  post 'leaderboard/unlike/:exercise_submission_id', to: 'dashboards#unlike', as: 'leaderboard_unlike'

  get 'documentation', to: 'documentation#index'

  get 'exercises/archived', to: 'exercises#archived', as: 'archived_exercises'
  post 'exercises/:id/archive', to: 'exercises#archive', as: 'archive_exercise'
  post 'exercises/:id/restore', to: 'exercises#restore', as: 'restore_exercise'

  resources :exercises
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OCR Tracker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.png') %>
    
    <style>
        .flash__alert   { color: red; }
        .flash__notice  { color: blue; }
        .flash__success { color: green; }
    </style>
  </head>

<% if !current_page?(new_user_session_path) %>
  <%#Admin Navbar%>
  <% unless !current_user.is_admin? %>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
      <%= link_to "OCR Tracker", root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Leaderboard", leaderboard_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "WOD", user_wod_path, class: 'nav-link' %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Management
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                <li><%= link_to "Exercises", exercises_path, class: 'nav-link' , style: "color: black"%></li>
                <li><%= link_to "New Post", posts_new_path, class: 'nav-link' , style: "color: black"%></li>
                <li><%= link_to "Set WOD", set_wod_path, class: 'nav-link' , style: "color: black"%></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "Permissions", permissions_path, class: 'nav-link' , style: "color: black"%></li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= "#{current_user.full_name}"%>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                <li><%= link_to "View Profile", profiles_path(current_user.id), class: 'nav-link' , style: "color: black"%></li>
                <li><%= link_to "Members", '/members', class: 'nav-link', style: "color: black"%></li>
                <li><%= link_to "Help", '/documentation', class: 'nav-link', style: "color: black"%></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, class: 'nav-link' , style: "color: black"%></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  <% end %>
  <%#User Navbar%>
  <% unless current_user.is_admin? %>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <%= link_to "OCR Tracker", root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Leaderboard", leaderboard_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "WOD", user_wod_path, class: 'nav-link' %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= "#{current_user.full_name}"%>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                <li><%= link_to "View Profile", profiles_path(current_user.id), class: 'nav-link' , style: "color: black"%></li>
                <li><%= link_to "Members", '/members', class: 'nav-link', style: "color: black"%></li>
                <%= link_to "Help", '/documentation', class: 'nav-link', style: "color: black" %>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, class: 'nav-link' , style: "color: black"%></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  <% end %>
<% else %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">OCR Tracker</a>
    </div>
  </nav>
<% end %>
  <body>
    <%= yield %>
  </body>
</html>